//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class admin
    {
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public admin()
        {
            this.requests = new HashSet<requests>();            
        }
        public int id_admin { get; set; }

        [Required(ErrorMessage = "Заполните поле")]
        [Display(Name = "Логин")]
        public string login_admin { get; set; }
        [Required(ErrorMessage = "Заполните поле")]
        [Display(Name = "Пароль")]
        public string password_admin { get; set; }
        [Required(ErrorMessage = "Заполните поле")]
        [Display(Name = "Фамилия")]
        public string surname { get; set; }
        [Required(ErrorMessage = "Заполните поле")]
        [Display(Name = "Имя")]
        public string name { get; set; }
        [Required(ErrorMessage = "Заполните поле")]
        [Display(Name = "Отчество")]
        public string middlename { get; set; }
        [Required(ErrorMessage = "Заполните поле")]
        [RegularExpression(@"^\+\d{1,2}\s+?\(\d{3,5}\)\s+?\d{1,3}-\d{2}-\d{2}$", ErrorMessage = "Номер должен соответствовать маске +7 (___) ___-__-__")]
       
        [Display(Name = "Телефон")]
        public string phone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<requests> requests { get; set; }
    }
}
